# Generated by Django 3.1.1 on 2020-09-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userrecord_adviser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='adviser',
        ),
    ]
