# Generated by Django 3.1.1 on 2020-10-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_init_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='type',
            new_name='record_type',
        ),
    ]
