# Generated by Django 3.1.1 on 2020-11-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_init_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='for_commercialization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='is_ip',
            field=models.BooleanField(default=False),
        ),
    ]
